### ISSUE TITLE
Can't find the document example

### ISSUE THREAD

**Issue by hourglasshoro** [k2tzumi/mob-timer-bot#3]
When I try to open the following URL in README, I get a message that the file is missing.

https://script.google.com/macros/s/miserarenaiyo/exec

**Comment by k2tzumi** [comment]
This URL was provided as an example and is not accessible. The explanation is not clear, so I have reviewed it.
https://github.com/k2tzumi/mob-timer-bot/commit/08ed02c39dab32f2d758948d201f3d9be3473d54
